
application: listaDominios_conectaGoogle
version: 1
runtime: python3
api_version: 1
threadsafe: yes

handlers:
- url: /css
  static_dir: static/css
- url: /imagens
  static_dir: static/imagens
- url: .*  # This regex directs all routes to main.app
  script: app.py
